modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "createoverprocessed"
version = "${version}"
displayName = "CreateOverprocessed Mod"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = "icon.png"

[[dependencies.createoverprocessed]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createoverprocessed]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createoverprocessed]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"